//
//  MoveToComponent.swift
//  Behavolve
//
//  Created by Michaël ATTAL on 24/04/2025.
//

import RealityKit

/// Moving mode used by `MovementSystem`.
enum MoveStrategy: UInt8, Sendable, Codable {
    case direct // straight line
    case pathfinding // follows way-points generated by PathfindingSystem (using A* ftm)
}

/// Attach to any entity that needs to move.
struct MoveToComponent: Component, Sendable {
    var destination: SIMD3<Float>
    var speed: Float
    var epsilon: Float
    var strategy: MoveStrategy
    var path: [SIMD3<Float>] = [] // way-points (set by PathfindingSystem)

    init(destination: SIMD3<Float>,
         speed: Float,
         epsilon: Float = 0.05,
         strategy: MoveStrategy = .direct)
    {
        self.destination = destination
        self.speed = speed
        self.epsilon = epsilon
        self.strategy = strategy
    }
}
